In [1]:
import camelot
import pandas as pd

# PDF file path
pdf_path = "groundwater.pdf"

# Extract tables from all pages
tables = camelot.read_pdf(pdf_path, pages="all", flavor="stream")

print("Total tables found:", tables.n)

# Store tables
dfs = []

for i, table in enumerate(tables):
    df = table.df
    dfs.append(df)

# Combine all tables
combined_df = pd.concat(dfs, ignore_index=True)

print("Raw data shape:", combined_df.shape)

print(combined_df.head())

c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:218: UserWarning: No tables found on page-2
  if self._document_has_no_text():
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 612.0, 792.0)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:218: UserWarning: No tables found on page-4
  if self._document_has_no_text():
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:124: UserWarning: page-5 is image-based, camelot only works on text-based pages.
  warnings.warn(
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:218: UserWarning: No tables found on page-6
  if self._document_has_no_text():
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:124: UserWarning: page-7 is image-based, camelot only works on text-based pages.
  warnings.warn(
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:218: UserWarning: No tables found on page-8
  if self._document_has_no_text():
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:124: UserWarning: page-9 is image-based, camelot only works on text-based pages.
  warnings.warn(
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:218: UserWarning: No tables found on page-10
  if self._document_has_no_text():
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:124: UserWarning: page-11 is image-based, camelot only works on text-based pages.
  warnings.warn(
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:218: UserWarning: No tables found on page-12
  if self._document_has_no_text():
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:218: UserWarning: No tables found on page-14
  if self._document_has_no_text():
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:218: UserWarning: No tables found on page-16
  if self._document_has_no_text():
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (55.18399999999998, 203.06799999999998, 542.804, 646.9245130434782)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:218: UserWarning: No tables found on page-18
  if self._document_has_no_text():
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:218: UserWarning: No tables found on page-22
  if self._document_has_no_text():
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 612.0, 792.0)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (61.99999999999987, 501.5959999999995, 537.3279999999999, 834.0048888888889)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 841.92, 595.32)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 841.92, 595.32)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (61.9952, 417.1159999999999, 537.2584000000003, 791.9648666666667)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (133.99999999999997, 70.556, 384.256, 280.38736000000006)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (134.0, 689.8759999999999, 400.216, 834.5601523809524)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (62.0, 434.756, 537.2584, 745.4001523809524)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (62.0, 459.7159999999998, 537.2596000000002, 726.3143854545455)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (61.99999999999997, 430.07600000000014, 537.2596000000007, 833.91004)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (61.99999999999994, 689.8759999999999, 537.2584000000003, 834.9184142857143)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (62.0, 670.5560000000003, 537.2608000000002, 832.4905454545454)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 841.92, 595.32)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (61.99999999999983, 64.07599999999996, 537.2596, 790.9581854545455)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 841.92, 595.32)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (62.0, 597.1160000000003, 544.3396000000004, 825.4175384615385)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 841.92, 595.32)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (61.99999999999997, 377.39599999999984, 544.3396000000005, 825.5426560000001)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (61.99999999999997, 242.75600000000023, 544.3396000000001, 783.4062157575758)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (69.08, 602.6359999999999, 542.9020000000006, 800.8070933333335)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (71.0, 446.7559999999999, 544.3384000000005, 646.3670933333332)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (69.07999999999998, 282.5960000000002, 544.3384000000004, 474.6470933333334)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (69.07999999999998, 640.3159999999999, 544.5796000000004, 799.9752444444446)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (67.15999999999994, 299.3959999999999, 538.9384000000006, 698.9352444444444)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (61.999999999999986, 464.03599999999966, 544.3408000000007, 824.2702685714287)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (62.0, 311.51600000000013, 544.3408000000004, 826.0692333333334)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (61.99999999999994, 331.31599999999986, 544.5796000000008, 826.2878459259259)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 595.32, 841.92)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 612.0, 792.0)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 792.0, 612.0)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)
c:\Users\pc\miniconda3\Lib\site-packages\camelot\parsers\base.py:238: UserWarning: No tables found in table area (0, 0, 612.0, 792.0)
  cols, rows, v_s, h_s = self._generate_columns_and_rows(bbox, user_cols)

Total tables found: 541
Raw data shape: (12577, 24)
                                           0    1    2    3    4    5    6   \
0                                  भारत सरकार  NaN  NaN  NaN  NaN  NaN  NaN
1                         Government of India  NaN  NaN  NaN  NaN  NaN  NaN
2                           जल शक्ति मंत्रालय  NaN  NaN  NaN  NaN  NaN  NaN
3                     Ministry of Jal Shakti,  NaN  NaN  NaN  NaN  NaN  NaN
4  जल संसाधन, नदी विकास और गंगा संरक्षण विभाग  NaN  NaN  NaN  NaN  NaN  NaN

    7    8    9   ...   14   15   16   17   18   19   20   21   22   23
0  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

[5 rows x 24 columns]

In [2]:
print("Total Columns:", combined_df.shape[1])
print(combined_df.columns)

Total Columns: 24
RangeIndex(start=0, stop=24, step=1)

In [3]:
combined_df = combined_df.replace("", pd.NA)

combined_df = combined_df.dropna(axis=1, how="all")

print(combined_df.shape)

(12577, 24)

In [4]:
df = combined_df.iloc[:, :6]   # first useful columns

In [5]:
print(combined_df.columns)

RangeIndex(start=0, stop=24, step=1)

In [6]:
df.columns = [
    "state",
    "district",
    "annual_recharge",
    "extractable_resource",
    "annual_extraction",
    "stage_of_development"
]

In [7]:
def classify(stage):
    try:
        stage = float(stage)
        if stage < 70:
            return "Safe"
        elif stage < 90:
            return "Semi Critical"
        elif stage < 100:
            return "Critical"
        else:
            return "Over Exploited"
    except:
        return None

df["category"] = df["stage_of_development"].apply(classify)

C:\Users\pc\AppData\Local\Temp\ipykernel_13272\3698087583.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["category"] = df["stage_of_development"].apply(classify)

In [8]:
df

,state,district,annual_recharge,extractable_resource,annual_extraction,stage_of_development,category
0,भारत सरकार,NaN,NaN,NaN,NaN,NaN,Over Exploited
1,Government of India,NaN,NaN,NaN,NaN,NaN,Over Exploited
2,जल शक्ति मंत्रालय,NaN,NaN,NaN,NaN,NaN,Over Exploited
3,"Ministry of Jal Shakti,",NaN,NaN,NaN,NaN,NaN,Over Exploited
4,"जल संसाधन, नदी विकास और गंगा संरक्षण विभाग",NaN,NaN,NaN,NaN,NaN,Over Exploited
...,...,...,...,...,...,...,...
12572,<NA>,Faridabad.,NaN,NaN,NaN,NaN,Over Exploited
12573,Central Ground Water Board,NaN,NaN,NaN,NaN,NaN,Over Exploited
12574,"Bhujal Bhawan, NH-IV",NaN,NaN,NaN,NaN,NaN,Over Exploited
12575,Faridabad,NaN,NaN,NaN,NaN,NaN,Over Exploited
12576,Haryana - 121001,NaN,NaN,NaN,NaN,NaN,Over Exploited

In [9]:
df.isnull().sum()

state                   4957
district                6110
annual_recharge         5838
extractable_resource    5668
annual_extraction       7147
stage_of_development    7496
category                6401
dtype: int64

In [10]:
df = df.dropna()

print(f"Rows after removing null values: {df.shape[0]}")
print(f"Null values remaining: {df.isnull().sum().sum()}")

Rows after removing null values: 2060
Null values remaining: 0

In [11]:
df

,state,district,annual_recharge,extractable_resource,annual_extraction,stage_of_development,category
175,1,Safe,4951,73.39,16.51,66.57,Safe
176,2,Semi Critical,711,10.54,2.82,11.40,Safe
177,3,Critical,206,3.05,0.88,3.55,Safe
178,4,Over-Exploited,751,11.13,4.20,16.93,Safe
179,5,Saline,127,1.88,0.38,1.55,Safe
...,...,...,...,...,...,...,...
11774,32,Delhi,34,0,3,31,Safe
11775,33,Jammu And Kashmir,149,0,0,149,Over Exploited
11776,34,Lakshadweep,5,0,0,5,Safe
11777,35,Puducherry,8,0,0,8,Safe
11778,36,Ladakh,18,5,0,13,Safe

In [12]:
df.to_csv("groundwater_dataset.csv", index=False)

In [13]:
# ================================
# STEP 1: Convert numeric columns
# ================================
numeric_cols = [
    "annual_recharge",
    "extractable_resource",
    "annual_extraction",
    "stage_of_development"
]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# ================================
# STEP 2: Drop null values again (after conversion)
# ================================
df = df.dropna().reset_index(drop=True)

# ================================
# STEP 3: Add NEW ML-USEFUL FEATURES
# ================================

# 1️⃣ Extraction Ratio
df["extraction_ratio"] = df["annual_extraction"] / df["annual_recharge"]

# 2️⃣ Utilization Rate
df["utilization_rate"] = df["annual_extraction"] / df["extractable_resource"]

# 3️⃣ Stress Level (numeric form of stage)
df["stress_level"] = df["stage_of_development"] / 100

# 4️⃣ Risk Score (important ML feature)
df["risk_score"] = (
    df["extraction_ratio"] * 0.4 +
    df["utilization_rate"] * 0.4 +
    df["stress_level"] * 0.2
)

# ================================
# STEP 4: Final Cleaning
# ================================
df = df.replace([float("inf"), -float("inf")], pd.NA)
df = df.dropna().reset_index(drop=True)

# ================================
# STEP 5: Add Year Column
# ================================
df["year"] = 2024

# ================================
# STEP 6: Final Dataset Check
# ================================
print("\nFinal Dataset Info:\n")
print(df.info())

print("\nSample Data:\n")
print(df.head())

print("\nNo. of Rows:", df.shape[0])
print("No. of Columns:", df.shape[1])

# ================================
# STEP 7: Save Dataset
# ================================
df.to_csv("groundwater_ml_dataset.csv", index=False)

print("\n✅ CLEAN ML DATASET CREATED SUCCESSFULLY")

Final Dataset Info:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1932 entries, 0 to 1931
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   state                 1932 non-null   object
 1   district              1932 non-null   object
 2   annual_recharge       1932 non-null   float64
 3   extractable_resource  1932 non-null   float64
 4   annual_extraction     1932 non-null   float64
 5   stage_of_development  1932 non-null   float64
 6   category              1932 non-null   object
 7   extraction_ratio      1932 non-null   object
 8   utilization_rate      1932 non-null   object
 9   stress_level          1932 non-null   float64
 10  risk_score            1932 non-null   object
 11  year                  1932 non-null   int64
dtypes: float64(5), int64(1), object(6)
memory usage: 181.3+ KB
None

Sample Data:

  state        district  annual_recharge  extractable_resource  \
0     1            Safe           4951.0                 73.39
1     2   Semi Critical            711.0                 10.54
2     3        Critical            206.0                  3.05
3     4  Over-Exploited            751.0                 11.13
4     5          Saline            127.0                  1.88

   annual_extraction  stage_of_development category extraction_ratio  \
0              16.51                 66.57     Safe         0.003335
1               2.82                 11.40     Safe         0.003966
2               0.88                  3.55     Safe         0.004272
3               4.20                 16.93     Safe         0.005593
4               0.38                  1.55     Safe         0.002992

  utilization_rate  stress_level risk_score  year
0         0.224963        0.6657   0.224459  2024
1         0.267552        0.1140   0.131407  2024
2         0.288525        0.0355   0.124219  2024
3         0.377358        0.1693    0.18704  2024
4         0.202128        0.0155   0.085148  2024

No. of Rows: 1932
No. of Columns: 12

✅ CLEAN ML DATASET CREATED SUCCESSFULLY

C:\Users\pc\AppData\Local\Temp\ipykernel_13272\2257789906.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors='coerce')

In [14]:
df

,state,district,annual_recharge,extractable_resource,annual_extraction,stage_of_development,category,extraction_ratio,utilization_rate,stress_level,risk_score,year
0,1,Safe,4951.0,73.39,16.51,66.57,Safe,0.003335,0.224963,0.6657,0.224459,2024
1,2,Semi Critical,711.0,10.54,2.82,11.40,Safe,0.003966,0.267552,0.1140,0.131407,2024
2,3,Critical,206.0,3.05,0.88,3.55,Safe,0.004272,0.288525,0.0355,0.124219,2024
3,4,Over-Exploited,751.0,11.13,4.20,16.93,Safe,0.005593,0.377358,0.1693,0.18704,2024
4,5,Saline,127.0,1.88,0.38,1.55,Safe,0.002992,0.202128,0.0155,0.085148,2024
...,...,...,...,...,...,...,...,...,...,...,...,...
1927,24,Telangana,620.0,9.00,76.00,527.00,Over Exploited,0.122581,8.444444,5.2700,4.48081,2024
1928,26,Uttar Pradesh,836.0,22.00,12.00,802.00,Over Exploited,0.014354,0.545455,8.0200,1.827923,2024
1929,28,West Bengal,345.0,4.00,4.00,337.00,Over Exploited,0.011594,1.0,3.3700,1.078638,2024
1930,30,Chandigarh,1.0,1.00,0.00,0.00,Safe,0.0,0.0,0.0000,0.0,2024
1931,36,Ladakh,18.0,5.00,0.00,13.00,Safe,0.0,0.0,0.1300,0.026,2024